version: '3.4'

services:
  paymentservices:
    image: paymentservices
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
